<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionSeeder extends Seeder
{
    public function run(): void
    {
        $departments = DB::table('departments')->get()->keyBy('department_no');

        $positions = [
            ['position_no' => '50008126', 'position_description' => 'Head, Corporate ICT', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50008127', 'position_description' => 'Head, Corporate Labor Relations', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50008135', 'position_description' => 'Lead, Credit & Collection', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50008136', 'position_description' => 'Executive Secretary', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50008170', 'position_description' => 'Head, Quality Control', 'department_id' => $departments['MIEL100']->id],
            ['position_no' => '50008184', 'position_description' => 'Company Nurse', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50008214', 'position_description' => 'Head,Safety Management;SustainabilityOff', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50008217', 'position_description' => 'Systems Administration Specialist', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50008219', 'position_description' => 'Head, Controllership', 'department_id' => $departments['MIEE100']->id],
            ['position_no' => '50008221', 'position_description' => 'Area Head, MBI DU', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50008224', 'position_description' => 'Head, Miescor DUS & MBI General Manager', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50008253', 'position_description' => 'Head, SCM con as Head, Trading BU', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50009332', 'position_description' => 'Health, Special Programs & DataSpecialis', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50009452', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50010011', 'position_description' => 'Payroll Officer', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50014795', 'position_description' => 'Caretaker', 'department_id' => $departments['MIEB110']->id],
            ['position_no' => '50014800', 'position_description' => 'Company Physician', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50016633', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50016635', 'position_description' => 'Nurse', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50016682', 'position_description' => 'Head, SHE & Security of MLI', 'department_id' => $departments['MIEE150']->id],
            ['position_no' => '50016693', 'position_description' => 'QAC Engineer', 'department_id' => $departments['MIEL110']->id],
            ['position_no' => '50017098', 'position_description' => 'Project Control Engineer', 'department_id' => $departments['MIEE170']->id],
            ['position_no' => '50017147', 'position_description' => 'Sales and Account Management Specialist', 'department_id' => $departments['MIEP100']->id],
            ['position_no' => '50017825', 'position_description' => 'General Counsel', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50018150', 'position_description' => 'Head, Finance', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50018436', 'position_description' => 'Lead, Revenue Accounting', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50020100', 'position_description' => 'Lead, HR Data, Systems and Process', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50020102', 'position_description' => 'Head, MBI HR and HRBP of DUS', 'department_id' => $departments['MIEH100']->id],
            ['position_no' => '50020826', 'position_description' => 'General Admin Associate', 'department_id' => $departments['MIEB110']->id],
            ['position_no' => '50023493', 'position_description' => 'HR Business Partner', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50024907', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50025859', 'position_description' => 'Head, CBDI', 'department_id' => $departments['MIEH100']->id],
            ['position_no' => '50029084', 'position_description' => 'Business Process Analyst', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50030251', 'position_description' => 'Payroll Officer', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50030632', 'position_description' => 'Recruitment Lead, SS', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50031126', 'position_description' => 'QAC Engineer', 'department_id' => $departments['MIEL110']->id],
            ['position_no' => '50031127', 'position_description' => 'Head, Treasury', 'department_id' => $departments['MIEE100']->id],
            ['position_no' => '50032855', 'position_description' => 'Supply Chain Analyst', 'department_id' => $departments['MIED150']->id],
            ['position_no' => '50034187', 'position_description' => 'Lead, Payroll and Benefits', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50034781', 'position_description' => 'Legal Staff', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50037119', 'position_description' => 'Payroll Officer', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50038352', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50038788', 'position_description' => 'QAC Engineer', 'department_id' => $departments['MIEL120']->id],
            ['position_no' => '50039712', 'position_description' => 'Payroll Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50040326', 'position_description' => 'Recruitment Lead', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50040986', 'position_description' => 'Paralegal', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50040988', 'position_description' => 'ICT Technical Support Staff', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50040989', 'position_description' => 'ICT Technical Staff', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50041553', 'position_description' => 'Head,TEL BU,Bids & Proposal,ComServices', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50048201', 'position_description' => 'Caretaker', 'department_id' => $departments['MIEB110']->id],
            ['position_no' => '50051395', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50052998', 'position_description' => 'President & CEO', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50055300', 'position_description' => 'Head, Logistics', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50056478', 'position_description' => 'Head, Corporate HR & Transformation', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50056873', 'position_description' => 'Head, Process and Standards', 'department_id' => $departments['MIEL100']->id],
            ['position_no' => '50057127', 'position_description' => 'Mechanic', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50057436', 'position_description' => 'Labor Relations Associate', 'department_id' => $departments['MIEI110']->id],
            ['position_no' => '50057728', 'position_description' => 'Lead, Warehouse', 'department_id' => $departments['MIED150']->id],
            ['position_no' => '50057730', 'position_description' => 'Lead, Warehouse', 'department_id' => $departments['MIED150']->id],
            ['position_no' => '50057982', 'position_description' => 'QAC Engineer', 'department_id' => $departments['MIEL110']->id],
            ['position_no' => '50057983', 'position_description' => 'QAC Engineer', 'department_id' => $departments['MIEL110']->id],
            ['position_no' => '50057986', 'position_description' => 'Supply Chain Analyst', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50057993', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEE150']->id],
            ['position_no' => '50057994', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50057995', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIED150']->id],
            ['position_no' => '50057998', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIED150']->id],
            ['position_no' => '50058323', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50058362', 'position_description' => 'Lead, Project Cost Control', 'department_id' => $departments['MIEE170']->id],
            ['position_no' => '50058699', 'position_description' => 'Head, Logistics Services', 'department_id' => $departments['MIEE150']->id],
            ['position_no' => '50059418', 'position_description' => 'Lead, Project Accounting', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50059420', 'position_description' => 'Lead, Disbursement Accounting', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50059421', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50059422', 'position_description' => 'Lead, Financial Closing & Reporting', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50059423', 'position_description' => 'Lead, Risk Management', 'department_id' => $departments['MIEE100']->id],
            ['position_no' => '50059830', 'position_description' => 'Head, Miescor Utility Attachment', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50061301', 'position_description' => 'Head, Quality Assurance and Control', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50061937', 'position_description' => 'Head, Finance (MLI)', 'department_id' => $departments['MIEE150']->id],
            ['position_no' => '50062341', 'position_description' => 'Lead, Project Accounting', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50064648', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50064750', 'position_description' => 'Network Administration Specialist', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50064990', 'position_description' => 'Payroll Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50065273', 'position_description' => 'General Admin Associate', 'department_id' => $departments['MIEB110']->id],
            ['position_no' => '50065368', 'position_description' => 'Head, Eng\'g, Procurement, & Construction', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50066499', 'position_description' => 'Payroll Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50066515', 'position_description' => 'Recruitment Lead, DUAS', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50066730', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50066872', 'position_description' => 'Head, General Construction', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50066902', 'position_description' => 'Lead, Logistics Operations Support', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50067353', 'position_description' => 'Lead, Facilities and TWE', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50067613', 'position_description' => 'Head,Occupational Safety&Sustainability', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50067639', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50069082', 'position_description' => 'Head, Procurement', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50069624', 'position_description' => 'QAC Engineer', 'department_id' => $departments['MIEL120']->id],
            ['position_no' => '50071164', 'position_description' => 'Analyst', 'department_id' => $departments['MIEE120']->id],
            ['position_no' => '50071813', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50072155', 'position_description' => 'Application Security Lead', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50072415', 'position_description' => 'Marketing Specialist', 'department_id' => $departments['MIEP100']->id],
            ['position_no' => '50072416', 'position_description' => 'Corporate Planning Analyst', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50072872', 'position_description' => 'Recruitment Lead', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50073012', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50073018', 'position_description' => 'Procurement Lead', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50073614', 'position_description' => 'Recruitment Officer', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50074073', 'position_description' => 'Payroll Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50074074', 'position_description' => 'Lead, Talent Dev & Engagement Speciali', 'department_id' => $departments['MIEH140']->id],
            ['position_no' => '50074271', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50074294', 'position_description' => 'Head, Financial Closing & Reporting', 'department_id' => $departments['MIEE100']->id],
            ['position_no' => '50074482', 'position_description' => 'Information Security Specialist', 'department_id' => $departments['MIEG110']->id],
            ['position_no' => '50074776', 'position_description' => 'Legal Counsel', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50075167', 'position_description' => 'Accounting Staff', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50075294', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50076887', 'position_description' => 'Benefits Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50077023', 'position_description' => 'Business Process Analyst', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50077061', 'position_description' => 'Head, Labor Relations', 'department_id' => $departments['MIEI100']->id],
            ['position_no' => '50077414', 'position_description' => 'HR Data Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50077822', 'position_description' => 'Legal Counsel', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50077949', 'position_description' => 'Lead, Tax Management', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50077953', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50078518', 'position_description' => 'HR System and Reporting Analyst', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50078666', 'position_description' => 'Analyst', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50078758', 'position_description' => 'Lead, HR Bus Part con Head, Tal Acq & Re', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50079529', 'position_description' => 'Accounting Officer', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50079530', 'position_description' => 'Accounting Officer', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50079533', 'position_description' => 'Accounting Officer', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50079534', 'position_description' => 'Accounting Officer', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50080169', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50080170', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50080171', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50080246', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50080779', 'position_description' => 'Supply Chain Analyst', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50082322', 'position_description' => 'Payroll Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50082501', 'position_description' => 'Lead, Fleet', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50083881', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50083884', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50083893', 'position_description' => 'Supply Chain Analyst', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50084456', 'position_description' => 'HR Business Partner', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50084458', 'position_description' => 'Sales and Account Management Specialist', 'department_id' => $departments['MIEP100']->id],
            ['position_no' => '50084939', 'position_description' => 'Accounting Staff', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50085010', 'position_description' => 'Head, Corporate Services', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50085405', 'position_description' => 'Accounting Staff', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50085811', 'position_description' => 'Head, MBI Procurement', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50086259', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50086438', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50086439', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50086542', 'position_description' => 'Recruitment Officer', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50087102', 'position_description' => 'Technical Support Specialist', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50087218', 'position_description' => 'Logistics Analyst', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50087297', 'position_description' => 'Analyst', 'department_id' => $departments['MIEE120']->id],
            ['position_no' => '50087426', 'position_description' => 'Accounting Officer', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50087433', 'position_description' => 'Head, MLI Human Resources', 'department_id' => $departments['MIEE150']->id],
            ['position_no' => '50088059', 'position_description' => 'Full Stack Developer', 'department_id' => $departments['MIEG120']->id],
            ['position_no' => '50088201', 'position_description' => 'Safety Officer', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50088631', 'position_description' => 'Logistic Staff Engineer', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50088637', 'position_description' => 'Legal Counsel', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50088733', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50088734', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50088896', 'position_description' => 'Supply Chain Analyst', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50088898', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50089154', 'position_description' => 'Sales and Account Management Specialist', 'department_id' => $departments['MIEP100']->id],
            ['position_no' => '50090435', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50090445', 'position_description' => 'Talent Development & Engagement Speciali', 'department_id' => $departments['MIEH140']->id],
            ['position_no' => '50090683', 'position_description' => 'Head, Operations Group', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50090854', 'position_description' => 'Lead HR Business Partner', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50090855', 'position_description' => 'HR Business Partner', 'department_id' => $departments['MIEH180']->id],
            ['position_no' => '50090905', 'position_description' => 'Business Process Analyst', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50090907', 'position_description' => 'Supply Chain Business Partner Associate', 'department_id' => $departments['MIED140']->id],
            ['position_no' => '50091076', 'position_description' => 'Talent Development &Engagement Specialis', 'department_id' => $departments['MIEH140']->id],
            ['position_no' => '50091301', 'position_description' => 'Importation Staff', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50091302', 'position_description' => 'Supply Chain Analyst', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50091686', 'position_description' => 'Lead, Disbursement', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50091687', 'position_description' => 'Environment Management Specialist', 'department_id' => $departments['MIEK100']->id],
            ['position_no' => '50091701', 'position_description' => 'Accounting Officer', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50091702', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50091982', 'position_description' => 'Lead, Labor Relations', 'department_id' => $departments['MIEI110']->id],
            ['position_no' => '50092034', 'position_description' => 'HR Data Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50092316', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50092451', 'position_description' => 'Head, Supply Chain Operations Support', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50092619', 'position_description' => 'Head, Supply Chain Business Partnering G', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50092677', 'position_description' => 'Security Operations Coordinator', 'department_id' => $departments['MIEI120']->id],
            ['position_no' => '50092813', 'position_description' => 'Labor Relations Associate', 'department_id' => $departments['MIEI110']->id],
            ['position_no' => '50092817', 'position_description' => 'Insurance Specialist', 'department_id' => $departments['MIEE100']->id],
            ['position_no' => '50092818', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50092819', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50093284', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50093516', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50093518', 'position_description' => 'Importation Staff', 'department_id' => $departments['MIED120']->id],
            ['position_no' => '50093648', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50093657', 'position_description' => 'Project Control Engineer', 'department_id' => $departments['MIEE170']->id],
            ['position_no' => '50093799', 'position_description' => 'Process Analyst', 'department_id' => $departments['MIEB120']->id],
            ['position_no' => '50094064', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50094292', 'position_description' => 'Head, MBI Finance', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50094293', 'position_description' => 'Head, ICT Operations', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50094295', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50094296', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50094694', 'position_description' => 'Project Control Engineer', 'department_id' => $departments['MIEE170']->id],
            ['position_no' => '50094825', 'position_description' => 'Procurement Lead', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50094826', 'position_description' => 'Procurement Lead', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50095202', 'position_description' => 'Project Control Engineer', 'department_id' => $departments['MIEE170']->id],
            ['position_no' => '50095253', 'position_description' => 'Application Security Officer', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50095361', 'position_description' => 'Auditor', 'department_id' => $departments['MIEC100']->id],
            ['position_no' => '50095673', 'position_description' => 'Purchaser', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50095813', 'position_description' => 'Head, Security Services', 'department_id' => $departments['MIEI120']->id],
            ['position_no' => '50095814', 'position_description' => 'Corporate Planning Analyst', 'department_id' => $departments['MIEB120']->id],
            ['position_no' => '50095815', 'position_description' => 'Security Operations Coordinator', 'department_id' => $departments['MIEI120']->id],
            ['position_no' => '50095998', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50096131', 'position_description' => 'Head, Corporate Audit', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50096132', 'position_description' => 'Accounting Staff', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50096133', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50096135', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50096195', 'position_description' => 'Recruitment Officer', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50096235', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50096236', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50096268', 'position_description' => 'Benefits Officer', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50096972', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50097618', 'position_description' => 'Lead, Engagement', 'department_id' => $departments['MIEH140']->id],
            ['position_no' => '50097964', 'position_description' => 'Logistic Staff Engineer', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50098027', 'position_description' => 'Purchaser', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50098227', 'position_description' => 'Supply Chain Business Partner Associate', 'department_id' => $departments['MIED140']->id],
            ['position_no' => '50098232', 'position_description' => 'Importation Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50098823', 'position_description' => 'Project Control Engineer', 'department_id' => $departments['MIEE170']->id],
            ['position_no' => '50098845', 'position_description' => 'Consultant', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50098891', 'position_description' => 'Recruitment Officer', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50099280', 'position_description' => 'Paralegal', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50099375', 'position_description' => 'Logistics Associate', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50099710', 'position_description' => 'Information Security Specialist', 'department_id' => $departments['MIEG110']->id],
            ['position_no' => '50100237', 'position_description' => 'Materials Management Analyst', 'department_id' => $departments['MIED150']->id],
            ['position_no' => '50100315', 'position_description' => 'Recruitment Officer', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50100319', 'position_description' => 'Technical Support Associate', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50100331', 'position_description' => 'Process Analyst', 'department_id' => $departments['MIEB120']->id],
            ['position_no' => '50101132', 'position_description' => 'Accountant', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50101559', 'position_description' => 'Head, Utility Attachment Management', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50101576', 'position_description' => 'Recruitment Officer', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50101724', 'position_description' => 'Treasury Staff', 'department_id' => $departments['MIEE130']->id],
            ['position_no' => '50101972', 'position_description' => 'Purchaser', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50102113', 'position_description' => 'OD Associate', 'department_id' => $departments['MIEH180']->id],
            ['position_no' => '50102204', 'position_description' => 'Talent Development and Engagement Associ', 'department_id' => $departments['MIEH140']->id],
            ['position_no' => '50102260', 'position_description' => 'Logistic Staff Engineer', 'department_id' => $departments['MIEO100']->id],
            ['position_no' => '50102540', 'position_description' => 'Accounting Staff', 'department_id' => $departments['MIEE110']->id],
            ['position_no' => '50102603', 'position_description' => 'Recruitment Lead', 'department_id' => $departments['MIEH170']->id],
            ['position_no' => '50103255', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50103257', 'position_description' => 'HR Business Partner', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50103258', 'position_description' => 'HR Business Partner', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50103259', 'position_description' => 'HR Business Partner', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50103260', 'position_description' => 'HRBP Staff', 'department_id' => $departments['MIEH160']->id],
            ['position_no' => '50103262', 'position_description' => 'Head, MLI Human Resources', 'department_id' => $departments['MIEE150']->id],
            ['position_no' => '50103263', 'position_description' => 'Head, MBI Human Resources', 'department_id' => $departments['MIEH100']->id],
            ['position_no' => '50103468', 'position_description' => 'ICT Technical Support Staff', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50103472', 'position_description' => 'Supply Chain Business Partner', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50104113', 'position_description' => 'Procurement Staff', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50104365', 'position_description' => 'Head, Corporate ICT', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50104722', 'position_description' => 'Payroll Associate', 'department_id' => $departments['MIEH110']->id],
            ['position_no' => '50104882', 'position_description' => 'Purchaser', 'department_id' => $departments['MIED110']->id],
            ['position_no' => '50105204', 'position_description' => 'Head, Infrastructure and Security Manage', 'department_id' => $departments['MIEG130']->id],
            ['position_no' => '50105205', 'position_description' => 'Head, Solutions Development', 'department_id' => $departments['MIEG120']->id],
            ['position_no' => '50105206', 'position_description' => 'Web App Developer', 'department_id' => $departments['MIEG120']->id],
            ['position_no' => '50105207', 'position_description' => 'Web App Developer', 'department_id' => $departments['MIEG120']->id],
            ['position_no' => '50105514', 'position_description' => 'Head, MBI Human Resources', 'department_id' => $departments['MIEE140']->id],
            ['position_no' => '50105520', 'position_description' => 'Legal Counsel', 'department_id' => $departments['MIEF100']->id],
            ['position_no' => '50105774', 'position_description' => 'Analyst', 'department_id' => $departments['MIEE120']->id],
            ['position_no' => '50105943', 'position_description' => 'Consultant', 'department_id' => $departments['MIEQ100']->id],
            ['position_no' => '50106091', 'position_description' => 'Executive Assistant', 'department_id' => $departments['MIEA100']->id],
            ['position_no' => '50106124', 'position_description' => 'Compliance Officer', 'department_id' => $departments['MIEA100']->id],
        ];

        DB::table('positions')->insert($positions);
    }
}
