<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\RequestingOffice;


class RequestingOfficeSeeder extends Seeder
{
    public function run(): void
    {
        $offices = [
            'Office of the Chief Operating Officer',
            'Corporate Social Responsibility Office',
            'Internal Audit',
            'Data Privacy',
            'Seconded Employees',
            'External and Government Affairs',
            'Investor Relations',
            'Business Development',
            'Business Continuity Management',
            'Office of the Chief Revenue Officer',
            'OH - MPower',
            'Retail Sales',
            'Meralco - Ecozone Power',
            'OH - Legal',
            'OH - Legal Operations Support',
            'Local Government Affairs and Special Projects',
            'Litigation Team 1',
            'Litigation Team 2',
            'Tax and Labor',
            'OH - Corporate Legal Services',
            'Paralegal Services',
            'OH - Finance',
            'Treasury for Subsidiaries & Other Business Units',
            'Accounting Operations and Control',
            'OH - Tax, Realty and Contract Management',
            'Realty',
            'OH - Treasury',
            'Investment & Debt Management',
            'Cash Management',
            'Corporate Governance',
            'Corporate Compliance',
            'OH - Human Resources',
            'Subsidiaries HR',
            'Networks HR',
            'Revenue HR',
            'Shared Services HR',
            'OH - Employee Relations',
            'Talent Management',
            'OH - HR Operations',
            'Talent Resourcing',
            'Compensation Design and Rewards',
            'Benefits Services',
            'HR Technology, Process and Data Management',
            'Organization Development',
            'Learning and Development',
            'OH - Learning & Development',
            'Technical Training',
            'Labor Relations',
            'OH - Information, Communication, Technology & Transformation',
            'Program Management',
            'Customer Contact Systems',
            'OH - ICT Governance',
            'OH - Infrastructure and Operations Management',
            'ICT Support Services',
            'OH - Telecommunications',
            'Data Solutions',
            'OH - DU Regulatory Management',
            'Tariff Management',
            'Utility Economics',
            'Regulatory Legal Case Management',
            'Regulatory Risk and Compliance',
            'Regulatory Relations',
            'Regulatory Legal Contract Management',
            'OH - Corporate Communications',
            'Public Relations',
            'Communications Strategy and Analysis',
            'Advocacy Communication Management',
            'Security',
            'FSGS Contract Management',
            'Facilities Design and Project Management',
            'Non-Electric Assets and Technology Management',
            'Project Management',
            'Operations and Maintenance',
            'OH - Supply Chain Management',
            'Materials Management Office',
            'Supply Chain Operations Support',
            'OH - DU Business Development',
            'OH - Customer Retail Services',
            'Competitive Market Group',
            'Renewables Program Management Organization (inactive)',
            'CRS Program Management',
            'OH - Enterprise & National Government',
            'Enterprise - Commercial and Conglomerates',
            'OH - BIZ Partners Group',
            'South Biz Area',
            'OH - North Business Area',
            'OH - South Business Area',
            'Rosario Business Center',
            'OH - Central Business Area',
            'OH - Marketing and Brand Experience',
            'Customer Experience Marketing',
            'Consumer Insights & Experience Design',
            'Brand Experience Management',
            'OH - Customer Process and Revenue Assurance',
            'Revenue Assurance and Fraud Management',
            'Customer Process, Analytics and Reporting',
            'OH - Commercial Operations',
            'Billing Operations & Analytics',
            'Customer Payments',
            'Contract Management Office',
            'OH - Customer Care Group',
            'Customer Interaction Management Group',
            'OH - Commercial Strategy Management and Energy Solutions',
            'Smart Energy Solutions',
            'E-Mobility Solutions',
            'Renewable Energy Solutions',
            'OH - Networks',
            'Balintawak Sector - Operations',
            'Pasig Logistics',
            'OH - Integrated Asset Management',
            'Substation Services Asset Management',
            'Distribution Services Asset Management',
            'Operations Services Management',
            'OH - Energy Management',
            'System Control Center',
            'Energy Sourcing Organization',
            'Network Asset Planning',
            'OH - Network Planning and Design',
            'Embedded Generation Integration Planning',
            'Data Management and Analytics',
            'Technology Strategy and Program Management',
            'Contract and Outsourcing Management',
            'Environment, Safety and Health Management',
            'OH - Corporate Sustainability Office',
            'Sustainability Strategy and Reporting',
            'Sustainability Programs and Communications',
            'Sustainability Programs',
            'Chief Information Security Officer',
            'Compliance, Policies and Standards',
            'Operations Technology Security Support (inactive)',
            'Security Platform Service Management',
            'Energy Management',
        ];

        foreach ($offices as $officeName) {
            RequestingOffice::firstOrCreate(
                ['office_name' => $officeName]
            );
        }

        $this->command->info('Fleet Requestor Offices seeded: ' . count($offices) . ' records');
    }
}
